discounts:
  mode: online
  quarkus-base:
    fullnameOverride: "discounts"
    image:
      tag: v1.0.1
    version: none
    rollouts:
      enabled: true
      blueGreen:
        enabled: true
        activeService: "discounts-umbrella-online"
        previewService: "discounts-umbrella-offline"
  fullnameOverride: "discounts"
  
products:
  mode: online
  quarkus-base:
    image:
      tag: v1.0.1
    replicaCount: 2
    fullnameOverride: "products"
    version: none
    rollouts:
      enabled: true
      blueGreen:
        enabled: true
        activeService: "products-umbrella-online"
        previewService: "products-umbrella-offline"
  fullnameOverride: "products"

global:
  namespace: test
  #needed for rollouts analysis









