discounts-blue:
  nameOverride: discounts-umbrella
  fullnameOverride: "discounts-blue"
  quarkus-base:
    replicaCount: 2
    nameOverride: discounts-umbrella
    fullnameOverride: "discounts-blue"
    log:
      level: DEBUG
    version: blue
    image:
      # Overrides the image tag whose default is the chart appVersion.
      tag: "latest"
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/q/metrics"
discounts-green:
  nameOverride: discounts-umbrella
  fullnameOverride: "discounts-green"
  quarkus-base:
    nameOverride: discounts-umbrella
    fullnameOverride: "discounts-green"
    log:
      level: DEBUG 
    version: green
    image:
      tag: "latest"
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/q/metrics" 
discountsNetworkingOnline:
  nameOverride: discounts-umbrella
  fullnameOverride: "discounts-umbrella-online"
  router:
    enabled: false
discountsNetworkingOffline:
  nameOverride: discounts-umbrella
  fullnameOverride: "discounts-umbrella-offline"
  router:
    enabled: false
    
products-blue:
  nameOverride: products-umbrella
  fullnameOverride: "products-blue"
  quarkus-base:
    replicaCount: 2
    nameOverride: products-umbrella
    fullnameOverride: "products-blue"
    log:
      level: DEBUG
    version: blue
    image:
      tag: "latest"
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/q/metrics"
products-green:
  nameOverride: products-umbrella
  fullnameOverride: "products-green"
  quarkus-base:
    nameOverride: products-umbrella
    fullnameOverride: "products-green"
    log:
      level: DEBUG
    version: green
    image:
      tag: "latest"
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/q/metrics"
productsNetworkingOnline:
  nameOverride: products-umbrella
  fullnameOverride: products-umbrella-online

productsNetworkingOffline:
  nameOverride: products-umbrella
  fullnameOverride: "products-umbrella-offline"

global:
  istio:
    enabled: false

nameOverride: "shop-umbrella" 

fullnameOverride: ""






