discounts:
  nameOverride: discounts-umbrella
  fullnameOverride: "discounts"
  quarkus-base:
    replicaCount: 2
    nameOverride: discounts-umbrella
    fullnameOverride: "discounts"
    log:
      level: DEBUG
    version: active
    image:
      # Overrides the image tag whose default is the chart appVersion.
      tag: "latest"
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/q/metrics"

discountsNetworkingOnline:
  nameOverride: discounts-umbrella
  fullnameOverride: "discounts-umbrella-online"
  router:
    enabled: false
discountsNetworkingOffline:
  nameOverride: discounts-umbrella
  fullnameOverride: "discounts-umbrella-offline"
  router:
    enabled: false
    
products:
  nameOverride: products-umbrella
  fullnameOverride: "products"
  quarkus-base:
    replicaCount: 2
    nameOverride: products-umbrella
    fullnameOverride: "products"
    log:
      level: DEBUG
    version: active
    image:
      tag: "latest"
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/q/metrics"

productsNetworkingOnline:
  nameOverride: products-umbrella
  fullnameOverride: products-umbrella-online

productsNetworkingOffline:
  nameOverride: products-umbrella
  fullnameOverride: "products-umbrella-offline"

global:
  istio:
    enabled: false

nameOverride: "shop-umbrella" 

fullnameOverride: ""






