tags:
  discountsNetworkingOffline: false
  productsNetworkingOffline: false

discounts:
  mode: online
  quarkus-base:
    fullnameOverride: "discounts"
    image:
      tag: v1.0.1
    version: none
    rollouts:
      enabled: true
      canary:
        steps:
          - setWeight: 50
          - pause:
              duration: 1m
  fullnameOverride: "discounts"
    
products:
  mode: online
  quarkus-base:
    version: none
    replicaCount: 4
    fullnameOverride: "products"
    rollouts:
      enabled: true
  fullnameOverride: "products"
  
global:
  namespace: test
  #needed for rollouts analysis









