apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "products.fullname" $ }}-configmap-env"
  labels:
    {{- include "products.labels" $ | nindent 4 }}
data:
  application.mode: {{ .Values.mode }} 

  quarkus.rest-client.discounts-api.url: {{  printf "http://discounts-umbrella-%s:8080" .Values.mode }}
  quarkus.rest-client.discounts-api.scope: javax.inject.RequestScoped
  #quarkus.rest-client.discounts-api.connection-pool-size: "50"
  quarkus.rest-client.discounts-api.connection-ttl: "1"
