apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "quarkus.labels" . | nindent 4 }}
  name: "{{ include "quarkus.fullname" . }}-prometheus-monitor"
spec:
  endpoints:
  - interval: 30s
    targetPort: 8080
    path: /q/metrics
    scheme: http
  selector:
    matchLabels:
      {{- include "quarkus.labels" . | nindent 6 }}
