apiVersion: v1
kind: Service
metadata:
  name: {{ include "quarkus.fullname" . }}
  labels:
    {{- include "quarkus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "quarkus.selectorLabels" . | nindent 4 }}
    {{- with .Values.version }}
    version: {{ . }}
    {{- end }}
